# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileemployee',
            name='department',
            field=models.CharField(max_length=30, verbose_name='Departamento'),
        ),
    ]
